image:  docker/compose:latest
services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  script:
    - apk add --no-cache git
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG . -f docker/dockerfile-builder
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

